---
- name: Configurar Classic Client
  hosts: all
  become: yes
  tasks:
    - name: Instalar net-tools (para comando arp) e iperf
      apt:
        name: 
          - net-tools
          - iperf
        state: present
        update_cache: yes

    - block:
        - name: Del default route
          command: ip route del default

        - name: Levantar interface enp0s8
          command: ip link set enp0s8 up
        
        - name: Adjuste arp table
          command: arp -i enp0s8 -s 192.168.57.20 08:00:27:EE:EE:EE

        - name: Desabilitar ECN
          command: "sysctl -w net.ipv4.tcp_ecn=0"

        - name: Adicionar rota est√°tica para 192.168.57.20
          command: "ip route add 192.168.57.20 dev enp0s8"

    
      ignore_errors: yes
